import { BoxProps } from "../grid/box";

export const boxes: BoxProps[] = [
  {
    id: "a",
    minCols: 1,
    minRows: 1,
    preferredCols: 2,
    preferredRows: 2,
    priority: 1,
    label: "Box A",
  },
  {
    id: "b",
    minCols: 2,
    minRows: 1,
    preferredCols: 2,
    preferredRows: 2,
    priority: 2,
    label: "Box B",
  },
  {
    id: "c",
    minCols: 1,
    minRows: 2,
    preferredCols: 2,
    preferredRows: 2,
    priority: 3,
    label: "Box C",
  },
  {
    id: "d",
    minCols: 1,
    minRows: 1,
    preferredCols: 1,
    preferredRows: 1,
    priority: 4,
    label: "Box D",
  },
  {
    id: "e",
    minCols: 2,
    minRows: 2,
    preferredCols: 3,
    preferredRows: 2,
    priority: 5,
    label: "Box E",
  },
  {
    id: "f",
    minCols: 1,
    minRows: 1,
    preferredCols: 1,
    preferredRows: 1,
    priority: 6,
    label: "Box F",
  },
  {
    id: "g",
    minCols: 2,
    minRows: 1,
    preferredCols: 3,
    preferredRows: 1,
    priority: 7,
    label: "Box G",
  },
  {
    id: "h",
    minCols: 1,
    minRows: 3,
    preferredCols: 1,
    preferredRows: 3,
    priority: 8,
    label: "Box H",
  },
  {
    id: "i",
    minCols: 3,
    minRows: 2,
    preferredCols: 3,
    preferredRows: 3,
    priority: 9,
    label: "Box I",
  },
  {
    id: "j",
    minCols: 1,
    minRows: 1,
    preferredCols: 2,
    preferredRows: 1,
    priority: 10,
    label: "Box J",
  },
  {
    id: "k",
    minCols: 1,
    minRows: 2,
    preferredCols: 1,
    preferredRows: 2,
    priority: 11,
    label: "Box K",
  },
  {
    id: "l",
    minCols: 2,
    minRows: 2,
    preferredCols: 2,
    preferredRows: 3,
    priority: 12,
    label: "Box L",
  },
];
