// import { DateTransformer } from "@/app/transformers.ts/date-transformer";
import { z } from "zod";
// import { JourneyVectorSchema } from "./journey-vector";
// import { TimeAdjustmentSchema } from "./time-adjustment";
// import { ArrivingDepartingSchema } from "../arriving-departing";

export const JourneyPlannerSchema = z.object({
  // journeys: [
  //   {
  //     startDateTime: DateTransformer,
  //     duration: z.number(),
  //     arrivalDateTime: DateTransformer,
  //     description: z.string(),
  //     alternativeRoute: z.boolean(),
  //     legs: [
  //       {
  //         duration: z.number(),
  //         speed: z.string(),
  //         instruction: {
  //           summary: z.string(),
  //           detailed: z.string(),
  //           steps: [
  //             {
  //               description: z.string(),
  //               turnDirection: z.string(),
  //               streetName: z.string(),
  //               distance: z.number(),
  //               cumulativeDistance: z.number(),
  //               skyDirection: z.number(),
  //               skyDirectionDescription: z.string(),
  //               cumulativeTravelTime: z.number(),
  //               latitude: z.number(),
  //               longitude: z.number(),
  //               pathAttribute: {
  //                 name: z.string(),
  //                 value: z.string(),
  //               },
  //               descriptionHeading: z.string(),
  //               trackType: z.string(),
  //               travelTime: z.number(),
  //               atcoCode: z.string(),
  //             },
  //           ],
  //         },
  //         obstacles: [
  //           {
  //             type: z.string(),
  //             incline: z.string(),
  //             stopId: z.number(),
  //             position: z.string(),
  //           },
  //         ],
  //         departureTime: DateTransformer,
  //         arrivalTime: DateTransformer,
  //         departurePoint: {
  //           lat: z.number(),
  //           lon: z.number(),
  //         },
  //         arrivalPoint: {
  //           lat: z.number(),
  //           lon: z.number(),
  //         },
  //         path: {
  //           lineString: z.string(),
  //           stopPoints: [
  //             {
  //               id: z.string(),
  //               name: z.string(),
  //               uri: z.string(),
  //               fullName: z.string(),
  //               type: z.string(),
  //               crowding: {
  //                 passengerFlows: [
  //                   {
  //                     timeSlice: z.string(),
  //                     value: z.number(),
  //                   },
  //                 ],
  //                 trainLoadings: [
  //                   {
  //                     line: z.string(),
  //                     lineDirection: z.string(),
  //                     platformDirection: z.string(),
  //                     direction: z.string(),
  //                     naptanTo: z.string(),
  //                     timeSlice: z.string(),
  //                     value: z.number(),
  //                   },
  //                 ],
  //               },
  //               routeType: z.string(),
  //               status: z.string(),
  //               motType: z.string(),
  //               network: z.string(),
  //             },
  //           ],
  //           elevation: [
  //             {
  //               distance: z.number(),
  //               startLat: z.number(),
  //               startLon: z.number(),
  //               endLat: z.number(),
  //               endLon: z.number(),
  //               heightFromPreviousPoint: z.number(),
  //               gradient: z.number(),
  //             },
  //           ],
  //         },
  //         routeOptions: [
  //           {
  //             id: z.string(),
  //             name: z.string(),
  //             directions: [z.string()],
  //             lineIdentifier: {
  //               id: z.string(),
  //               name: z.string(),
  //               uri: z.string(),
  //               fullName: z.string(),
  //               type: z.string(),
  //               crowding: {
  //                 passengerFlows: [
  //                   {
  //                     timeSlice: z.string(),
  //                     value: z.number(),
  //                   },
  //                 ],
  //                 trainLoadings: [
  //                   {
  //                     line: z.string(),
  //                     lineDirection: z.string(),
  //                     platformDirection: z.string(),
  //                     direction: z.string(),
  //                     naptanTo: z.string(),
  //                     timeSlice: z.string(),
  //                     value: z.number(),
  //                   },
  //                 ],
  //               },
  //               routeType: z.string(),
  //               status: z.string(),
  //               motType: z.string(),
  //               network: z.string(),
  //             },
  //             direction: z.string(),
  //           },
  //         ],
  //         mode: {
  //           id: z.string(),
  //           name: z.string(),
  //           uri: z.string(),
  //           fullName: z.string(),
  //           type: z.string(),
  //           crowding: {
  //             passengerFlows: [
  //               {
  //                 timeSlice: z.string(),
  //                 value: z.number(),
  //               },
  //             ],
  //             trainLoadings: [
  //               {
  //                 line: z.string(),
  //                 lineDirection: z.string(),
  //                 platformDirection: z.string(),
  //                 direction: z.string(),
  //                 naptanTo: z.string(),
  //                 timeSlice: z.string(),
  //                 value: z.number(),
  //               },
  //             ],
  //           },
  //           routeType: z.string(),
  //           status: z.string(),
  //           motType: z.string(),
  //           network: z.string(),
  //         },
  //         disruptions: [
  //           {
  //             category: z.string(),
  //             type: z.string(),
  //             categoryDescription: z.string(),
  //             description: z.string(),
  //             summary: z.string(),
  //             additionalInfo: z.string(),
  //             created: DateTransformer,
  //             lastUpdate: DateTransformer,
  //             affectedRoutes: [
  //               {
  //                 id: z.string(),
  //                 lineId: z.string(),
  //                 routeCode: z.string(),
  //                 name: z.string(),
  //                 lineString: z.string(),
  //                 direction: z.string(),
  //                 originationName: z.string(),
  //                 destinationName: z.string(),
  //                 via: {
  //                   ordinal: z.number(),
  //                   stopPoint: {
  //                     naptanId: z.string(),
  //                     platformName: z.string(),
  //                     indicator: z.string(),
  //                     stopLetter: z.string(),
  //                     modes: [z.string()],
  //                     icsCode: z.string(),
  //                     smsCode: z.string(),
  //                     stopType: z.string(),
  //                     stationNaptan: z.string(),
  //                     accessibilitySummary: z.string(),
  //                     hubNaptanCode: z.string(),
  //                     lines: [
  //                       {
  //                         id: z.string(),
  //                         name: z.string(),
  //                         uri: z.string(),
  //                         fullName: z.string(),
  //                         type: z.string(),
  //                         crowding: {
  //                           passengerFlows: [
  //                             {
  //                               timeSlice: z.string(),
  //                               value: z.number(),
  //                             },
  //                           ],
  //                           trainLoadings: [
  //                             {
  //                               line: z.string(),
  //                               lineDirection: z.string(),
  //                               platformDirection: z.string(),
  //                               direction: z.string(),
  //                               naptanTo: z.string(),
  //                               timeSlice: z.string(),
  //                               value: z.number(),
  //                             },
  //                           ],
  //                         },
  //                         routeType: z.string(),
  //                         status: z.string(),
  //                         motType: z.string(),
  //                         network: z.string(),
  //                       },
  //                     ],
  //                     lineGroup: [
  //                       {
  //                         naptanIdReference: z.string(),
  //                         stationAtcoCode: z.string(),
  //                         lineIdentifier: [z.string()],
  //                       },
  //                     ],
  //                     lineModeGroups: [
  //                       {
  //                         modeName: z.string(),
  //                         lineIdentifier: [z.string()],
  //                       },
  //                     ],
  //                     fullName: z.string(),
  //                     naptanMode: z.string(),
  //                     status: z.boolean(),
  //                     individualStopId: z.string(),
  //                     id: z.string(),
  //                     url: z.string(),
  //                     commonName: z.string(),
  //                     distance: z.number(),
  //                     placeType: z.string(),
  //                     additionalProperties: [
  //                       {
  //                         category: z.string(),
  //                         key: z.string(),
  //                         sourceSystemKey: z.string(),
  //                         value: z.string(),
  //                         modified: DateTransformer,
  //                       },
  //                     ],
  //                     children: [
  //                       {
  //                         id: z.string(),
  //                         url: z.string(),
  //                         commonName: z.string(),
  //                         distance: z.number(),
  //                         placeType: z.string(),
  //                         additionalProperties: [
  //                           {
  //                             category: z.string(),
  //                             key: z.string(),
  //                             sourceSystemKey: z.string(),
  //                             value: z.string(),
  //                             modified: DateTransformer,
  //                           },
  //                         ],
  //                         children: [{}],
  //                         childrenUrls: [z.string()],
  //                         lat: z.number(),
  //                         lon: z.number(),
  //                       },
  //                     ],
  //                     childrenUrls: [z.string()],
  //                     lat: z.number(),
  //                     lon: z.number(),
  //                   },
  //                 },
  //                 isEntireRouteSection: z.boolean(),
  //                 validTo: DateTransformer,
  //                 validFrom: DateTransformer,
  //                 routeSectionNaptanEntrySequence: [
  //                   {
  //                     ordinal: z.number(),
  //                     stopPoint: {
  //                       naptanId: z.string(),
  //                       platformName: z.string(),
  //                       indicator: z.string(),
  //                       stopLetter: z.string(),
  //                       modes: [z.string()],
  //                       icsCode: z.string(),
  //                       smsCode: z.string(),
  //                       stopType: z.string(),
  //                       stationNaptan: z.string(),
  //                       accessibilitySummary: z.string(),
  //                       hubNaptanCode: z.string(),
  //                       lines: [
  //                         {
  //                           id: z.string(),
  //                           name: z.string(),
  //                           uri: z.string(),
  //                           fullName: z.string(),
  //                           type: z.string(),
  //                           crowding: {
  //                             passengerFlows: [
  //                               {
  //                                 timeSlice: z.string(),
  //                                 value: z.number(),
  //                               },
  //                             ],
  //                             trainLoadings: [
  //                               {
  //                                 line: z.string(),
  //                                 lineDirection: z.string(),
  //                                 platformDirection: z.string(),
  //                                 direction: z.string(),
  //                                 naptanTo: z.string(),
  //                                 timeSlice: z.string(),
  //                                 value: z.number(),
  //                               },
  //                             ],
  //                           },
  //                           routeType: z.string(),
  //                           status: z.string(),
  //                           motType: z.string(),
  //                           network: z.string(),
  //                         },
  //                       ],
  //                       lineGroup: [
  //                         {
  //                           naptanIdReference: z.string(),
  //                           stationAtcoCode: z.string(),
  //                           lineIdentifier: [z.string()],
  //                         },
  //                       ],
  //                       lineModeGroups: [
  //                         {
  //                           modeName: z.string(),
  //                           lineIdentifier: [z.string()],
  //                         },
  //                       ],
  //                       fullName: z.string(),
  //                       naptanMode: z.string(),
  //                       status: z.boolean(),
  //                       individualStopId: z.string(),
  //                       id: z.string(),
  //                       url: z.string(),
  //                       commonName: z.string(),
  //                       distance: z.number(),
  //                       placeType: z.string(),
  //                       additionalProperties: [
  //                         {
  //                           category: z.string(),
  //                           key: z.string(),
  //                           sourceSystemKey: z.string(),
  //                           value: z.string(),
  //                           modified: DateTransformer,
  //                         },
  //                       ],
  //                       children: [
  //                         {
  //                           id: z.string(),
  //                           url: z.string(),
  //                           commonName: z.string(),
  //                           distance: z.number(),
  //                           placeType: z.string(),
  //                           additionalProperties: [
  //                             {
  //                               category: z.string(),
  //                               key: z.string(),
  //                               sourceSystemKey: z.string(),
  //                               value: z.string(),
  //                               modified: DateTransformer,
  //                             },
  //                           ],
  //                           children: [{}],
  //                           childrenUrls: [z.string()],
  //                           lat: z.number(),
  //                           lon: z.number(),
  //                         },
  //                       ],
  //                       childrenUrls: [z.string()],
  //                       lat: z.number(),
  //                       lon: z.number(),
  //                     },
  //                   },
  //                 ],
  //               },
  //             ],
  //             affectedStops: [
  //               {
  //                 naptanId: z.string(),
  //                 platformName: z.string(),
  //                 indicator: z.string(),
  //                 stopLetter: z.string(),
  //                 modes: [z.string()],
  //                 icsCode: z.string(),
  //                 smsCode: z.string(),
  //                 stopType: z.string(),
  //                 stationNaptan: z.string(),
  //                 accessibilitySummary: z.string(),
  //                 hubNaptanCode: z.string(),
  //                 lines: [
  //                   {
  //                     id: z.string(),
  //                     name: z.string(),
  //                     uri: z.string(),
  //                     fullName: z.string(),
  //                     type: z.string(),
  //                     crowding: {
  //                       passengerFlows: [
  //                         {
  //                           timeSlice: z.string(),
  //                           value: z.number(),
  //                         },
  //                       ],
  //                       trainLoadings: [
  //                         {
  //                           line: z.string(),
  //                           lineDirection: z.string(),
  //                           platformDirection: z.string(),
  //                           direction: z.string(),
  //                           naptanTo: z.string(),
  //                           timeSlice: z.string(),
  //                           value: z.number(),
  //                         },
  //                       ],
  //                     },
  //                     routeType: z.string(),
  //                     status: z.string(),
  //                     motType: z.string(),
  //                     network: z.string(),
  //                   },
  //                 ],
  //                 lineGroup: [
  //                   {
  //                     naptanIdReference: z.string(),
  //                     stationAtcoCode: z.string(),
  //                     lineIdentifier: [z.string()],
  //                   },
  //                 ],
  //                 lineModeGroups: [
  //                   {
  //                     modeName: z.string(),
  //                     lineIdentifier: [z.string()],
  //                   },
  //                 ],
  //                 fullName: z.string(),
  //                 naptanMode: z.string(),
  //                 status: z.boolean(),
  //                 individualStopId: z.string(),
  //                 id: z.string(),
  //                 url: z.string(),
  //                 commonName: z.string(),
  //                 distance: z.number(),
  //                 placeType: z.string(),
  //                 additionalProperties: [
  //                   {
  //                     category: z.string(),
  //                     key: z.string(),
  //                     sourceSystemKey: z.string(),
  //                     value: z.string(),
  //                     modified: DateTransformer,
  //                   },
  //                 ],
  //                 children: [
  //                   {
  //                     id: z.string(),
  //                     url: z.string(),
  //                     commonName: z.string(),
  //                     distance: z.number(),
  //                     placeType: z.string(),
  //                     additionalProperties: [
  //                       {
  //                         category: z.string(),
  //                         key: z.string(),
  //                         sourceSystemKey: z.string(),
  //                         value: z.string(),
  //                         modified: DateTransformer,
  //                       },
  //                     ],
  //                     children: [{}],
  //                     childrenUrls: [z.string()],
  //                     lat: z.number(),
  //                     lon: z.number(),
  //                   },
  //                 ],
  //                 childrenUrls: [z.string()],
  //                 lat: z.number(),
  //                 lon: z.number(),
  //               },
  //             ],
  //             closureText: z.string(),
  //           },
  //         ],
  //         plannedWorks: [
  //           {
  //             id: z.string(),
  //             description: z.string(),
  //             createdDateTime: DateTransformer,
  //             lastUpdateDateTime: DateTransformer,
  //           },
  //         ],
  //         distance: z.number(),
  //         isDisrupted: z.boolean(),
  //         hasFixedLocations: z.boolean(),
  //         scheduledDepartureTime: DateTransformer,
  //         scheduledArrivalTime: DateTransformer,
  //         interChangeDuration: z.string(),
  //         interChangePosition: z.string(),
  //       },
  //     ],
  //     fare: {
  //       totalCost: z.number(),
  //       fares: [
  //         {
  //           lowZone: z.number(),
  //           highZone: z.number(),
  //           cost: z.number(),
  //           chargeProfileName: z.string(),
  //           isHopperFare: z.boolean(),
  //           chargeLevel: z.string(),
  //           peak: z.number(),
  //           offPeak: z.number(),
  //           taps: [
  //             {
  //               atcoCode: z.string(),
  //               tapDetails: {
  //                 modeType: z.string(),
  //                 validationType: z.string(),
  //                 hostDeviceType: z.string(),
  //                 busRouteId: z.string(),
  //                 nationalLocationCode: z.number(),
  //                 tapTimestamp: DateTransformer,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //       caveats: [
  //         {
  //           text: z.string(),
  //           type: z.string(),
  //         },
  //       ],
  //     },
  //   },
  // ],
  // lines: z.array(
  //   z.object({
  //     id: z.string(),
  //     name: z.string(),
  //     modeName: z.string(),
  //     disruptions: [
  //       {
  //         category: z.string(),
  //         type: z.string(),
  //         categoryDescription: z.string(),
  //         description: z.string(),
  //         summary: z.string(),
  //         additionalInfo: z.string(),
  //         created: DateTransformer,
  //         lastUpdate: DateTransformer,
  //         affectedRoutes: [
  //           {
  //             id: z.string(),
  //             lineId: z.string(),
  //             routeCode: z.string(),
  //             name: z.string(),
  //             lineString: z.string(),
  //             direction: z.string(),
  //             originationName: z.string(),
  //             destinationName: z.string(),
  //             via: {
  //               ordinal: z.number(),
  //               stopPoint: {
  //                 naptanId: z.string(),
  //                 platformName: z.string(),
  //                 indicator: z.string(),
  //                 stopLetter: z.string(),
  //                 modes: [z.string()],
  //                 icsCode: z.string(),
  //                 smsCode: z.string(),
  //                 stopType: z.string(),
  //                 stationNaptan: z.string(),
  //                 accessibilitySummary: z.string(),
  //                 hubNaptanCode: z.string(),
  //                 lines: [
  //                   {
  //                     id: z.string(),
  //                     name: z.string(),
  //                     uri: z.string(),
  //                     fullName: z.string(),
  //                     type: z.string(),
  //                     crowding: {
  //                       passengerFlows: [
  //                         {
  //                           timeSlice: z.string(),
  //                           value: z.number(),
  //                         },
  //                       ],
  //                       trainLoadings: [
  //                         {
  //                           line: z.string(),
  //                           lineDirection: z.string(),
  //                           platformDirection: z.string(),
  //                           direction: z.string(),
  //                           naptanTo: z.string(),
  //                           timeSlice: z.string(),
  //                           value: z.number(),
  //                         },
  //                       ],
  //                     },
  //                     routeType: z.string(),
  //                     status: z.string(),
  //                     motType: z.string(),
  //                     network: z.string(),
  //                   },
  //                 ],
  //                 lineGroup: [
  //                   {
  //                     naptanIdReference: z.string(),
  //                     stationAtcoCode: z.string(),
  //                     lineIdentifier: [z.string()],
  //                   },
  //                 ],
  //                 lineModeGroups: [
  //                   {
  //                     modeName: z.string(),
  //                     lineIdentifier: [z.string()],
  //                   },
  //                 ],
  //                 fullName: z.string(),
  //                 naptanMode: z.string(),
  //                 status: z.boolean(),
  //                 individualStopId: z.string(),
  //                 id: z.string(),
  //                 url: z.string(),
  //                 commonName: z.string(),
  //                 distance: z.number(),
  //                 placeType: z.string(),
  //                 additionalProperties: [
  //                   {
  //                     category: z.string(),
  //                     key: z.string(),
  //                     sourceSystemKey: z.string(),
  //                     value: z.string(),
  //                     modified: DateTransformer,
  //                   },
  //                 ],
  //                 children: [
  //                   {
  //                     id: z.string(),
  //                     url: z.string(),
  //                     commonName: z.string(),
  //                     distance: z.number(),
  //                     placeType: z.string(),
  //                     additionalProperties: [
  //                       {
  //                         category: z.string(),
  //                         key: z.string(),
  //                         sourceSystemKey: z.string(),
  //                         value: z.string(),
  //                         modified: DateTransformer,
  //                       },
  //                     ],
  //                     children: [{}],
  //                     childrenUrls: [z.string()],
  //                     lat: z.number(),
  //                     lon: z.number(),
  //                   },
  //                 ],
  //                 childrenUrls: [z.string()],
  //                 lat: z.number(),
  //                 lon: z.number(),
  //               },
  //             },
  //             isEntireRouteSection: z.boolean(),
  //             validTo: DateTransformer,
  //             validFrom: DateTransformer,
  //             routeSectionNaptanEntrySequence: [
  //               {
  //                 ordinal: z.number(),
  //                 stopPoint: {
  //                   naptanId: z.string(),
  //                   platformName: z.string(),
  //                   indicator: z.string(),
  //                   stopLetter: z.string(),
  //                   modes: [z.string()],
  //                   icsCode: z.string(),
  //                   smsCode: z.string(),
  //                   stopType: z.string(),
  //                   stationNaptan: z.string(),
  //                   accessibilitySummary: z.string(),
  //                   hubNaptanCode: z.string(),
  //                   lines: [
  //                     {
  //                       id: z.string(),
  //                       name: z.string(),
  //                       uri: z.string(),
  //                       fullName: z.string(),
  //                       type: z.string(),
  //                       crowding: {
  //                         passengerFlows: [
  //                           {
  //                             timeSlice: z.string(),
  //                             value: z.number(),
  //                           },
  //                         ],
  //                         trainLoadings: [
  //                           {
  //                             line: z.string(),
  //                             lineDirection: z.string(),
  //                             platformDirection: z.string(),
  //                             direction: z.string(),
  //                             naptanTo: z.string(),
  //                             timeSlice: z.string(),
  //                             value: z.number(),
  //                           },
  //                         ],
  //                       },
  //                       routeType: z.string(),
  //                       status: z.string(),
  //                       motType: z.string(),
  //                       network: z.string(),
  //                     },
  //                   ],
  //                   lineGroup: [
  //                     {
  //                       naptanIdReference: z.string(),
  //                       stationAtcoCode: z.string(),
  //                       lineIdentifier: [z.string()],
  //                     },
  //                   ],
  //                   lineModeGroups: [
  //                     {
  //                       modeName: z.string(),
  //                       lineIdentifier: [z.string()],
  //                     },
  //                   ],
  //                   fullName: z.string(),
  //                   naptanMode: z.string(),
  //                   status: z.boolean(),
  //                   individualStopId: z.string(),
  //                   id: z.string(),
  //                   url: z.string(),
  //                   commonName: z.string(),
  //                   distance: z.number(),
  //                   placeType: z.string(),
  //                   additionalProperties: [
  //                     {
  //                       category: z.string(),
  //                       key: z.string(),
  //                       sourceSystemKey: z.string(),
  //                       value: z.string(),
  //                       modified: DateTransformer,
  //                     },
  //                   ],
  //                   children: [
  //                     {
  //                       id: z.string(),
  //                       url: z.string(),
  //                       commonName: z.string(),
  //                       distance: z.number(),
  //                       placeType: z.string(),
  //                       additionalProperties: [
  //                         {
  //                           category: z.string(),
  //                           key: z.string(),
  //                           sourceSystemKey: z.string(),
  //                           value: z.string(),
  //                           modified: DateTransformer,
  //                         },
  //                       ],
  //                       children: [{}],
  //                       childrenUrls: [z.string()],
  //                       lat: z.number(),
  //                       lon: z.number(),
  //                     },
  //                   ],
  //                   childrenUrls: [z.string()],
  //                   lat: z.number(),
  //                   lon: z.number(),
  //                 },
  //               },
  //             ],
  //           },
  //         ],
  //         affectedStops: [
  //           {
  //             naptanId: z.string(),
  //             platformName: z.string(),
  //             indicator: z.string(),
  //             stopLetter: z.string(),
  //             modes: [z.string()],
  //             icsCode: z.string(),
  //             smsCode: z.string(),
  //             stopType: z.string(),
  //             stationNaptan: z.string(),
  //             accessibilitySummary: z.string(),
  //             hubNaptanCode: z.string(),
  //             lines: [
  //               {
  //                 id: z.string(),
  //                 name: z.string(),
  //                 uri: z.string(),
  //                 fullName: z.string(),
  //                 type: z.string(),
  //                 crowding: {
  //                   passengerFlows: [
  //                     {
  //                       timeSlice: z.string(),
  //                       value: z.number(),
  //                     },
  //                   ],
  //                   trainLoadings: [
  //                     {
  //                       line: z.string(),
  //                       lineDirection: z.string(),
  //                       platformDirection: z.string(),
  //                       direction: z.string(),
  //                       naptanTo: z.string(),
  //                       timeSlice: z.string(),
  //                       value: z.number(),
  //                     },
  //                   ],
  //                 },
  //                 routeType: z.string(),
  //                 status: z.string(),
  //                 motType: z.string(),
  //                 network: z.string(),
  //               },
  //             ],
  //             lineGroup: [
  //               {
  //                 naptanIdReference: z.string(),
  //                 stationAtcoCode: z.string(),
  //                 lineIdentifier: [z.string()],
  //               },
  //             ],
  //             lineModeGroups: [
  //               {
  //                 modeName: z.string(),
  //                 lineIdentifier: [z.string()],
  //               },
  //             ],
  //             fullName: z.string(),
  //             naptanMode: z.string(),
  //             status: z.boolean(),
  //             individualStopId: z.string(),
  //             id: z.string(),
  //             url: z.string(),
  //             commonName: z.string(),
  //             distance: z.number(),
  //             placeType: z.string(),
  //             additionalProperties: [
  //               {
  //                 category: z.string(),
  //                 key: z.string(),
  //                 sourceSystemKey: z.string(),
  //                 value: z.string(),
  //                 modified: DateTransformer,
  //               },
  //             ],
  //             children: [
  //               {
  //                 id: z.string(),
  //                 url: z.string(),
  //                 commonName: z.string(),
  //                 distance: z.number(),
  //                 placeType: z.string(),
  //                 additionalProperties: [
  //                   {
  //                     category: z.string(),
  //                     key: z.string(),
  //                     sourceSystemKey: z.string(),
  //                     value: z.string(),
  //                     modified: DateTransformer,
  //                   },
  //                 ],
  //                 children: [{}],
  //                 childrenUrls: [z.string()],
  //                 lat: z.number(),
  //                 lon: z.number(),
  //               },
  //             ],
  //             childrenUrls: [z.string()],
  //             lat: z.number(),
  //             lon: z.number(),
  //           },
  //         ],
  //         closureText: z.string(),
  //       },
  //     ],
  //     created: DateTransformer,
  //     modified: DateTransformer,
  //     lineStatuses: [
  //       {
  //         id: z.number(),
  //         lineId: z.string(),
  //         statusSeverity: z.number(),
  //         statusSeverityDescription: z.string(),
  //         reason: z.string(),
  //         created: DateTransformer,
  //         modified: DateTransformer,
  //         validityPeriods: [
  //           {
  //             fromDate: DateTransformer,
  //             toDate: DateTransformer,
  //             isNow: z.boolean(),
  //           },
  //         ],
  //         disruption: {
  //           category: z.string(),
  //           type: z.string(),
  //           categoryDescription: z.string(),
  //           description: z.string(),
  //           summary: z.string(),
  //           additionalInfo: z.string(),
  //           created: DateTransformer,
  //           lastUpdate: DateTransformer,
  //           affectedRoutes: [
  //             {
  //               id: z.string(),
  //               lineId: z.string(),
  //               routeCode: z.string(),
  //               name: z.string(),
  //               lineString: z.string(),
  //               direction: z.string(),
  //               originationName: z.string(),
  //               destinationName: z.string(),
  //               via: {
  //                 ordinal: z.number(),
  //                 stopPoint: {
  //                   naptanId: z.string(),
  //                   platformName: z.string(),
  //                   indicator: z.string(),
  //                   stopLetter: z.string(),
  //                   modes: [z.string()],
  //                   icsCode: z.string(),
  //                   smsCode: z.string(),
  //                   stopType: z.string(),
  //                   stationNaptan: z.string(),
  //                   accessibilitySummary: z.string(),
  //                   hubNaptanCode: z.string(),
  //                   lines: [
  //                     {
  //                       id: z.string(),
  //                       name: z.string(),
  //                       uri: z.string(),
  //                       fullName: z.string(),
  //                       type: z.string(),
  //                       crowding: {
  //                         passengerFlows: [
  //                           {
  //                             timeSlice: z.string(),
  //                             value: z.number(),
  //                           },
  //                         ],
  //                         trainLoadings: [
  //                           {
  //                             line: z.string(),
  //                             lineDirection: z.string(),
  //                             platformDirection: z.string(),
  //                             direction: z.string(),
  //                             naptanTo: z.string(),
  //                             timeSlice: z.string(),
  //                             value: z.number(),
  //                           },
  //                         ],
  //                       },
  //                       routeType: z.string(),
  //                       status: z.string(),
  //                       motType: z.string(),
  //                       network: z.string(),
  //                     },
  //                   ],
  //                   lineGroup: [
  //                     {
  //                       naptanIdReference: z.string(),
  //                       stationAtcoCode: z.string(),
  //                       lineIdentifier: [z.string()],
  //                     },
  //                   ],
  //                   lineModeGroups: [
  //                     {
  //                       modeName: z.string(),
  //                       lineIdentifier: [z.string()],
  //                     },
  //                   ],
  //                   fullName: z.string(),
  //                   naptanMode: z.string(),
  //                   status: z.boolean(),
  //                   individualStopId: z.string(),
  //                   id: z.string(),
  //                   url: z.string(),
  //                   commonName: z.string(),
  //                   distance: z.number(),
  //                   placeType: z.string(),
  //                   additionalProperties: [
  //                     {
  //                       category: z.string(),
  //                       key: z.string(),
  //                       sourceSystemKey: z.string(),
  //                       value: z.string(),
  //                       modified: DateTransformer,
  //                     },
  //                   ],
  //                   children: [
  //                     {
  //                       id: z.string(),
  //                       url: z.string(),
  //                       commonName: z.string(),
  //                       distance: z.number(),
  //                       placeType: z.string(),
  //                       additionalProperties: [
  //                         {
  //                           category: z.string(),
  //                           key: z.string(),
  //                           sourceSystemKey: z.string(),
  //                           value: z.string(),
  //                           modified: DateTransformer,
  //                         },
  //                       ],
  //                       children: [{}],
  //                       childrenUrls: [z.string()],
  //                       lat: z.number(),
  //                       lon: z.number(),
  //                     },
  //                   ],
  //                   childrenUrls: [z.string()],
  //                   lat: z.number(),
  //                   lon: z.number(),
  //                 },
  //               },
  //               isEntireRouteSection: z.boolean(),
  //               validTo: DateTransformer,
  //               validFrom: DateTransformer,
  //               routeSectionNaptanEntrySequence: [
  //                 {
  //                   ordinal: z.number(),
  //                   stopPoint: {
  //                     naptanId: z.string(),
  //                     platformName: z.string(),
  //                     indicator: z.string(),
  //                     stopLetter: z.string(),
  //                     modes: [z.string()],
  //                     icsCode: z.string(),
  //                     smsCode: z.string(),
  //                     stopType: z.string(),
  //                     stationNaptan: z.string(),
  //                     accessibilitySummary: z.string(),
  //                     hubNaptanCode: z.string(),
  //                     lines: [
  //                       {
  //                         id: z.string(),
  //                         name: z.string(),
  //                         uri: z.string(),
  //                         fullName: z.string(),
  //                         type: z.string(),
  //                         crowding: {
  //                           passengerFlows: [
  //                             {
  //                               timeSlice: z.string(),
  //                               value: z.number(),
  //                             },
  //                           ],
  //                           trainLoadings: [
  //                             {
  //                               line: z.string(),
  //                               lineDirection: z.string(),
  //                               platformDirection: z.string(),
  //                               direction: z.string(),
  //                               naptanTo: z.string(),
  //                               timeSlice: z.string(),
  //                               value: z.number(),
  //                             },
  //                           ],
  //                         },
  //                         routeType: z.string(),
  //                         status: z.string(),
  //                         motType: z.string(),
  //                         network: z.string(),
  //                       },
  //                     ],
  //                     lineGroup: [
  //                       {
  //                         naptanIdReference: z.string(),
  //                         stationAtcoCode: z.string(),
  //                         lineIdentifier: [z.string()],
  //                       },
  //                     ],
  //                     lineModeGroups: [
  //                       {
  //                         modeName: z.string(),
  //                         lineIdentifier: [z.string()],
  //                       },
  //                     ],
  //                     fullName: z.string(),
  //                     naptanMode: z.string(),
  //                     status: z.boolean(),
  //                     individualStopId: z.string(),
  //                     id: z.string(),
  //                     url: z.string(),
  //                     commonName: z.string(),
  //                     distance: z.number(),
  //                     placeType: z.string(),
  //                     additionalProperties: [
  //                       {
  //                         category: z.string(),
  //                         key: z.string(),
  //                         sourceSystemKey: z.string(),
  //                         value: z.string(),
  //                         modified: DateTransformer,
  //                       },
  //                     ],
  //                     children: [
  //                       {
  //                         id: z.string(),
  //                         url: z.string(),
  //                         commonName: z.string(),
  //                         distance: z.number(),
  //                         placeType: z.string(),
  //                         additionalProperties: [
  //                           {
  //                             category: z.string(),
  //                             key: z.string(),
  //                             sourceSystemKey: z.string(),
  //                             value: z.string(),
  //                             modified: DateTransformer,
  //                           },
  //                         ],
  //                         children: [{}],
  //                         childrenUrls: [z.string()],
  //                         lat: z.number(),
  //                         lon: z.number(),
  //                       },
  //                     ],
  //                     childrenUrls: [z.string()],
  //                     lat: z.number(),
  //                     lon: z.number(),
  //                   },
  //                 },
  //               ],
  //             },
  //           ],
  //           affectedStops: [
  //             {
  //               naptanId: z.string(),
  //               platformName: z.string(),
  //               indicator: z.string(),
  //               stopLetter: z.string(),
  //               modes: [z.string()],
  //               icsCode: z.string(),
  //               smsCode: z.string(),
  //               stopType: z.string(),
  //               stationNaptan: z.string(),
  //               accessibilitySummary: z.string(),
  //               hubNaptanCode: z.string(),
  //               lines: [
  //                 {
  //                   id: z.string(),
  //                   name: z.string(),
  //                   uri: z.string(),
  //                   fullName: z.string(),
  //                   type: z.string(),
  //                   crowding: {
  //                     passengerFlows: [
  //                       {
  //                         timeSlice: z.string(),
  //                         value: z.number(),
  //                       },
  //                     ],
  //                     trainLoadings: [
  //                       {
  //                         line: z.string(),
  //                         lineDirection: z.string(),
  //                         platformDirection: z.string(),
  //                         direction: z.string(),
  //                         naptanTo: z.string(),
  //                         timeSlice: z.string(),
  //                         value: z.number(),
  //                       },
  //                     ],
  //                   },
  //                   routeType: z.string(),
  //                   status: z.string(),
  //                   motType: z.string(),
  //                   network: z.string(),
  //                 },
  //               ],
  //               lineGroup: [
  //                 {
  //                   naptanIdReference: z.string(),
  //                   stationAtcoCode: z.string(),
  //                   lineIdentifier: [z.string()],
  //                 },
  //               ],
  //               lineModeGroups: [
  //                 {
  //                   modeName: z.string(),
  //                   lineIdentifier: [z.string()],
  //                 },
  //               ],
  //               fullName: z.string(),
  //               naptanMode: z.string(),
  //               status: z.boolean(),
  //               individualStopId: z.string(),
  //               id: z.string(),
  //               url: z.string(),
  //               commonName: z.string(),
  //               distance: z.number(),
  //               placeType: z.string(),
  //               additionalProperties: [
  //                 {
  //                   category: z.string(),
  //                   key: z.string(),
  //                   sourceSystemKey: z.string(),
  //                   value: z.string(),
  //                   modified: DateTransformer,
  //                 },
  //               ],
  //               children: [
  //                 {
  //                   id: z.string(),
  //                   url: z.string(),
  //                   commonName: z.string(),
  //                   distance: z.number(),
  //                   placeType: z.string(),
  //                   additionalProperties: [
  //                     {
  //                       category: z.string(),
  //                       key: z.string(),
  //                       sourceSystemKey: z.string(),
  //                       value: z.string(),
  //                       modified: DateTransformer,
  //                     },
  //                   ],
  //                   children: [{}],
  //                   childrenUrls: [z.string()],
  //                   lat: z.number(),
  //                   lon: z.number(),
  //                 },
  //               ],
  //               childrenUrls: [z.string()],
  //               lat: z.number(),
  //               lon: z.number(),
  //             },
  //           ],
  //           closureText: z.string(),
  //         },
  //       },
  //     ],
  //     routeSections: z.array(
  //       z.object({
  //         routeCode: z.string(),
  //         name: z.string(),
  //         direction: z.string(),
  //         originationName: z.string(),
  //         destinationName: z.string(),
  //         originator: z.string(),
  //         destination: z.string(),
  //         serviceType: z.string(),
  //         validTo: DateTransformer,
  //         validFrom: DateTransformer,
  //       })
  //     ),
  //     serviceTypes: z.array(
  //       z.object({
  //         name: z.string(),
  //         uri: z.string(),
  //       })
  //     ),
  //     crowding: z.object({
  //       passengerFlows: z.array(
  //         z.object({
  //           timeSlice: z.string(),
  //           value: z.number(),
  //         })
  //       ),
  //       trainLoadings: z.array(
  //         z.object({
  //           line: z.string(),
  //           lineDirection: z.string(),
  //           platformDirection: z.string(),
  //           direction: z.string(),
  //           naptanTo: z.string(),
  //           timeSlice: z.string(),
  //           value: z.number(),
  //         })
  //       ),
  //     }),
  //   })
  // ),
  // cycleHireDockingStationData: z.object({
  //   originNumberOfBikes: z.number(),
  //   destinationNumberOfBikes: z.number(),
  //   originNumberOfEmptySlots: z.number(),
  //   destinationNumberOfEmptySlots: z.number(),
  //   originId: z.string(),
  //   destinationId: z.string(),
  // }),
  // stopMessages: z.array(z.string()),
  // recommendedMaxAgeMinutes: z.number(),
  // searchCriteria: z.object({
  //   dateTime: DateTransformer,
  //   dateTimeType: ArrivingDepartingSchema,
  //   timeAdjustments: TimeAdjustmentSchema,
  // }),
  // journeyVector: JourneyVectorSchema,
});

export type JourneyPlanner = z.infer<typeof JourneyPlannerSchema>;
